#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer	true

xinput set-prop 'ASUE1409:00 04F3:3157 Touchpad' 'libinput Natural Scrolling Enabled' 1
xinput set-prop 'Logitech Wireless Mouse' 'libinput Accel Speed' -0.8

$HOME/.config/polybar/launch.sh

feh --bg-fill $HOME/.config/backgrounds/82.jpg

xsetroot -cursor_name left_ptr &

picom &
xinput set-prop 'ASUE1409:00 04F3:3157 Touchpad' 'libinput Tapping Enabled' 1

xset s 360 300 &
xss-lock -n $HOME/.config/bspwm/suspender.sh -- i3lock -i $HOME/.config/backgrounds/91_red.png -n & 

