version = 3
final_space = true

[palette]
  blue = '#8CAAEE'
  closer = 'p:os'
  lavender = '#BABBF1'
  os = '#ACB0BE'
  pink = '#F4B8E4'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:os'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = 'p:blue'
    type = 'session'
    style = 'plain'
    display = false

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = '{{ .HEAD }} '
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ''

[transient_prompt]
  background = "transparent"
  template = ' '

