version = 3
final_space = true

[palette]
  blue = '#8CAAEE'
  closer = 'p:os'
  lavender = '#BABBF1'
  os = '#ACB0BE'
  pink = '#F4B8E4'
  red = '#FF0000'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:os'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .UserName }} '
    foreground = 'p:blue'
    type = 'session'
    style = 'plain'
    display = false

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

  [[blocks.segments]]
    template = '{{if .Env.TMUX}}tmux {{end}}'
    foreground = 'yellow'
    type = 'text'
    style = 'plain'


    [blocks.segments.properties]
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    type = "python"
    style = "plain"
  foreground = "#3365ff"
    template = " {{ .Full }} "

  [[blocks.segments]]
    type = "julia"
    style = "plain"
    foreground = "#906cff"
template = " {{ .Full }} "

  [[blocks.segments]]
    type = "java"
    style = "plain"
    foreground = "#FFCC00"
    template = " {{ .Full }} " 

  [[blocks.segments]]
    type = "rust"
    style = "plain"
    foreground = "#FF7700"
    template = " {{ .Full }} "


  [[blocks.segments]]
    template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'



    [blocks.segments.properties]
      source = "cli"
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']

    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  template = '❯ '
  type = 'status'
  style = 'plain'
  foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']
  always_enabled = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    template = '{{ div .Ms 1000 }}s'


    [blocks.segments.properties]
      threshold = 5000
