#!/bin/bash


rofi_command="rofi -theme $HOME/.config/polybar/scripts/themes/powermenu_alt.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=" Apagar"
reboot=" Reiniciar"
# lock=" Lock"
suspend=" Suspender"
logout="󰠜 Cerrar Sesion"

# Variable passed to rofi
# options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"
options="$reboot\n$shutdown\n$suspend\n$logout"

chosen="$(echo -e "$options" | $rofi_command -p "System" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    # $lock)
    #     i3lock
    #     ;;
    $suspend)
        # mpc -q pause
        amixer set Master mute
        systemctl suspend
        ;;
    $logout)
        bspc quit
        ;;
esac

