#!/usr/bin/env bash

set -euo pipefail

if [[ $# -eq 1 ]]; then
    selected="$1"
else
    selected="$(find "$HOME" -mindepth 1 -maxdepth 6 -type d | "$HOME/.fzf/bin/fzf" --height 40% --layout reverse --border top)"
fi

[[ -z "${selected:-}" ]] && exit 0

selected_name="$(basename "$selected" | tr . _)"

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -n "${TMUX:-}" ]]; then
    tmux switch-client -t "$selected_name"
else
    tmux attach-session -t "$selected_name"
fi
